### PR TITLE
Rename binary units according to IEC 60027 and add decimal units (SI)

### LINKED ISSUE #28: bytes package is not ISO/IEC 80000 and IEEE 1541 complient
according to Clause 4 of the [ISO/IEC 80000](https://github.com/labstack/gommon/issues/28#issue-392304417) standard and [IEEE 1541](https://en.wikipedia.org/wiki/IEEE_1541-2002)
among other things, the SI prefixes strictly refer to powers of ten and should not be used to indicate binary multiples

instead the Ki,Mi,Gi,.. prefixes should be used to indicate power of 2s

more on: https://en.wikipedia.org/wiki/Binary_prefix#IEC_prefixes

proposed solution:
change the current units from Si prefixes to Binary prefixes (KB->KiB,MB->MiB,GB->GiB,..) 
and then (optionally) add support for Si units

### PR DESCRIPTION
**Pull request by muXxer**
This PR fixes #28

### CODE REVIEW

**Comment by muXxer** [comment]
@vishr maybe you can have a look at this PR? :)
Thank you! :)

**Comment by muXxer** [comment]
4 months pending? :(

**Comment by aldas** [comment]
@muXxer it looks good but please change both `Format()` method signatures back as they were and I will merge this PR. 
This is unnecessary breaking change. If you know which `PrefixType` you want - you can call specific method also.

**Comment by muXxer** [comment]
Oh I just saw your comment now @aldas :sweat_smile: 

Is it really a breaking change, since the method signatures were extended by a variadic parameter?
If you don't pass the variadic parameter, it defaults back to the former behaviour.

**Comment by aldas** [comment]
This is unlikely but if someone has made interface for `Bytes.Format(b int64) string` that previous `Bytes` struct satisfied with its public method - then this is a breaking change.

**Comment by muXxer** [comment]
@aldas 
Sorry it took so long, almost forgot about that PR :)
Shouldn't be breaking now in terms of public methods.

**Comment by aldas** [comment]
better late than never

**Pull request merged**
